### ISSUE TITLE
How do I  submit job to spark operator from Jupyter notebook?

### ISSUE THREAD

**Issue by suresh-j2** [GoogleCloudPlatform/spark-on-k8s-operator#1351]
I have installed Spark operator in my K8s cluster. In the same cluster I have my notebook pod also running. Now I want to submit Spark Application job using Notebook. What's the right configuration for Pyspark?

**Comment by enricorotundo** [comment]
It seems this operator doesn't support that because `.spec.deployMode` can only be set to `cluster`, `as client is not currently implemented` (see [User Guide](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/74ea1c86c9a595e6c1c8a0c2c40a50bf89288ede/docs/user-guide.md#specifying-deployment-mode)).

@suresh-j2 you may want to give https://github.com/JahstreetOrg/spark-on-kubernetes-helm a try as it comes with Jupyter Notebooks although is not actively being developed.

**Comment by Wh1isper** [comment]
Hi, I've developed a module for deploying the latest 3.4.0 server-client model with support for direct PySpark Session connections!

Perhaps you could try this out.

https://github.com/Wh1isper/sparglim#spark-connect-server-on-k8s
