### ISSUE TITLE
Allow sparkctl flags for create being specified inside the application yaml

### ISSUE THREAD

**Issue by mrow4a** [GoogleCloudPlatform/spark-on-k8s-operator#143]
Currently, flags as `--upload-to`, `--project` and `--namespace` are passed separately from application yaml file. Could it be an interesting addition, to allow in `sparkctl create` to define these parameters inside the yaml? 

This way SparkApplication yaml could specify which gcp project (in case of s3 - profile) to use, and location to upload dependencies for this specific app.

**Comment by liyinan926** [comment]
The reason those are specified through flags is the jars/files are local to the client running `sparkctl`. The controller typically runs in a k8s cluster and therefore doesn't have access to the files.  Defining them in the application spec probably makes little sense from the controller perspective because the controller cannot do much with those dependencies. Thoughts?

**Comment by mrow4a** [comment]
Oh, well - this was not much of the intention. I thought more about preparsing yaml at sparkctl, and submitting the adjusted to controller.

**Comment by liyinan926** [comment]
Got it. That could work with an optional field in the spec for specifying how to handle local dependencies. Particularly, `--namespace` is not really needed as the yaml itself can specify that.

**Comment by liyinan926** [comment]
Is this still relevant?
