### ISSUE TITLE
Changed the import paths to use github.com/GoogleCloudPlatform/spark-on-k8s-operator instead of k8s.io

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#154]

**Comment by scotthew1** [comment]
adding to this now that go 1.11 is in the wild... the current import paths do not work with the `go.mod` since k8s.io/spark-on-k8s-operator is private

```
go: converting Gopkg.lock: stat k8s.io/spark-on-k8s-operator@f8485b3b2a989c6253d183ab9dc3ba0ec510018e: git fetch -f https://github.com/kubernetes/spark-on-k8s-operator refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /Users/scott/go/pkg/mod/cache/vcs/3337089f6a6a4a705dd4ecf247fb5cf2d40f5f66fbe51e03a99619929eb00c4f: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

currently `go.mod` does not provide the anything like the [source override](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#source) in dep that allowed us to work around this issue.

**Comment by liyinan926** [comment]
@scotthew1 will fix this soon.

**Comment by liyinan926** [comment]
The go import path has been fixed.
