### ISSUE TITLE
SparkApp CR object not updated

### ISSUE THREAD

**Issue by yuchaoran2011** [GoogleCloudPlatform/spark-on-k8s-operator#453]
We have two SparkApps that are started together and running concurrently. When one of them is updated with a new job image, the CRD object is supposed to enter a PENDING_RERUN state and then re-submitted for execution. But it seems to never get to SUBMITTED state. Instead we saw that the old driver pod was never deleted and the new driver pod was never started. 

We tried a single SparkApp and two SparkApps running serially. Both worked. It's just the aforementioned scenario that failed. Any idea what the cause would be? Does it have anything to do with the number of controller threads? Note that two SparkApps do have different names, so it would be surprising that one of them might interfere/conflict with another.

Below are the logs we saw:

**Comment by yuchaoran2011** [comment]
[spark-job-upgrade.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/3011504/spark-job-upgrade.log)

**Comment by liyinan926** [comment]
For the problematic application, was the driver created successfully even though the state was not updated to `SUBMITTED`?

**Comment by yuchaoran2011** [comment]
No. The app is stuck in `PENDING_RERUN`.

**Comment by liyinan926** [comment]
That's weird. The most interesting thing in the logs is the following:

`trying to resubmit an already submitted SparkApplication spark-resilience-test/spark-resilience-test-rs-ingress`

This kind of warning is only printed when a duplicated submission is triggered by an update and the duplicated submission failed because the driver pod already exists.

**Comment by yuchaoran2011** [comment]
The reason that the update and hence the re-submission failed is because the old driver pod was not deleted. The question is why wasn't it? We are still trying to figure out if it's because the deletion failed or it simply wasn't invoked at all.

**Comment by liyinan926** [comment]
Do you have access to the k8s master logs? If so, you might be able to see what's going on with the deletion. The fact that the app transitioned to state `PENDING_RERUN` means it must have gone through the `INVALIDATING` state where deletion of the resources should have been requested. The reason why the app remained in `PENDING_RERUN` state is likely because the resource still existed.

**Comment by liyinan926** [comment]
Can this be closed?

**Comment by yuchaoran2011** [comment]
A colleague of mine initially reported this issue. But he now has a workaround and hasn't got time to revisit the issue.

**Comment by yuchaoran2011** [comment]
We figured out what the bug is. The deletion request was indeed not issued because:
1. When the sparkapp state entered into INVALIDATING, the driver pod name was not set, causing the deletion to not happen (To delete a pod, its name has to be supplied).
2. When the sparkapp state transitioned from INVALIDATING to PENDING_RERUN, there was an if statement to check whether resources (e.g. pod and service) associated with the previous sparkapp has been cleaned up. This check failed to do its job again because the pod name of the old sparkapp was not available.
I'll issue a PR to fix it.
