### ISSUE TITLE
What the difference between cores and core request

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#581]
Cores - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/b0a4d1c923951161a753c1bee0837cac4b6bccea/pkg/apis/sparkoperator.k8s.io/v1beta1/types.go#L343

CoreRequest - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/b0a4d1c923951161a753c1bee0837cac4b6bccea/pkg/apis/sparkoperator.k8s.io/v1beta1/types.go#L432

**Comment by liyinan926** [comment]
`Cores` is the equivalent of `spark.[driver|executor].cores`. `CoreRequest` is exclusively for specifying the cpu request for executors. The value of `cores` is used for that if `coreRequest` is not set. The value of `cores` (`spark.executor.cores`) is additionally used by Spark to determine the task parallelism along with `spark.task.cpus`.

**Comment by AceHack** [comment]
How do I set a CPU limit?

**Comment by AceHack** [comment]
Also can you please point to some docs or explain in more detail.  I still don't really understand how CoreRequest and Cores and spark.task.cpus work in combination.  Thanks.

**Comment by liyinan926** [comment]
Do you more questions on this or can this be closed? Here's what I recommend:

1. If you need to use a value for executor cpu request that is not integral, e.g., 0.5 or 500m, use `coreRequest`. Otherwise, `cores` gets the job done and it defaults to 1. You can still choose to set `cores` for tuning task parallelism, even if you set `coreRequest`.
2. If you don't need more than one core per task, leave `spark.task.cpus` empty.
