### ISSUE TITLE
Starting many jobs causes a resource deadlock where drivers are executing but all executors pending

### ISSUE THREAD

**Issue by doctapp** [GoogleCloudPlatform/spark-on-k8s-operator#594]
Pushing say 10 `SparkApplication` at the same time causes a deadlock currently if the drivers gobble up all the cluster resources. This is caused because all drivers are allocated first without any provision for the executors. Once the executors try allocating their own resources they become pending as no SparkApplication can ever complete.

The Spark Operator should provision the driver and executors of a Spark application in the same phase (at least reserve the correct amount) to prevent a resource deadlock.

Any thoughts?

Thanks

**Comment by liyinan926** [comment]
This is a problem due to the way Spark applications are scheduled and a limitation of the default Kubernetes scheduler. For Spark on Kubernetes applications, the executor pods are requested by the drivers so the driver need to start running first before they can provision any executor pods. From the perspective of the default scheduler, it has no knowledge of this and will try to schedule the driver pods when asked. It's likely that by the time when the drivers request executor pods, there's no resources available to schedule the executors. 

We recently added a couple of enhancements that will help mitigate this issue. One is integration with Volcano, a Kubernetes native batch scheduler. See #585 and https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/567. The other is a new webhook for resource quota enforcement. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#enabling-resource-quota-enforcement.

**Comment by doctapp** [comment]
Excellent, thanks! I'll follow the Volcano work closely and will try the resource quota.

**Comment by liyinan926** [comment]
Closing this. Feel free to reopen if needed.
