### ISSUE TITLE
Automatic scaling of executors 

### ISSUE THREAD

**Issue by vishnugs** [GoogleCloudPlatform/spark-on-k8s-operator#631]
Hello,
Would like to know configuration for automatic addition/scaling of executors if the load is high on the system ?

**Comment by runzhliu** [comment]
@vishnugs we have tried this feature https://github.com/apache/spark/pull/24817, works well for now.

**Comment by liyinan926** [comment]
@vishnugs Spark on Kubernetes does not yet support dynamic resource allocation, due to the lack an external shuffle service implementation in the Kubernetes mode. SPARK-27963 (implemented in https://github.com/apache/spark/pull/24817) provides an alternative to enable dynamic resource allocation without an external shuffle service. We do plan to support this feature. See #616.

**Comment by vishnugs** [comment]
@runzhliu , how can i add the configuration for the same ?

**Comment by liyinan926** [comment]
@vishnugs first of all, you will need to use a Spark Docker image built from the latest master of Spark. Secondly, you will need to set `spark.dynamicAllocation.shuffleTracking.enabled=true` to enable the feature.

**Comment by runzhliu** [comment]
@vishnugs that's right, only available on the latest master branch, except you move that commit to your private branch.

**Comment by liyinan926** [comment]
This related to #616. Closing this and feel free to comment on #616 for questions. Thanks!

**Comment by Chethu7781** [comment]
@liyinan926  where should i set this? spark.dynamicAllocation.shuffleTracking.enabled=true in master node or spark-submit command
