### ISSUE TITLE
Spark doesn't pick up spark-defaults.conf from sparkConfigMap.

### ISSUE THREAD

**Issue by ransoor2** [GoogleCloudPlatform/spark-on-k8s-operator#691]
I created a config map with a key named spark-defaults.conf. 
The config map is mounted correctly at /etc/spark/conf, and I can also see that SPARK_CONF_DIR=/etc/spark/conf. However, spark doesn't pick up configuration from this file.

It works using the other way thru spec.sparkConf.

**Comment by liyinan926** [comment]
This is an known issue with Spark 2.4+. In Spark 2.4+, the Kubernetes-specific submission client (in the Spark repo) creates an internal ConfigMap for the driver and mounts it into the driver pod, and sets `SPARK_CONF_DIR` to point to the mount path. That internal ConfigMap contains Spark config properties. Using the `sparkConfigMap` feature in the operator with Spark 2.4+ conflicts with the internal ConfigMap and that's why it didn't work for you. For now, please use `spec.sparkConf`.

**Comment by ransoor2** [comment]
Thanks!

**Comment by dyno** [comment]
same issue even on spark 3.3.1.
