### ISSUE TITLE
Spark operator for spark-2.3.4

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#780]
Is there any spark operator available for spark-2.3.4?
If yes, can we use enableWebhook=true option with spark-2.3.4?
@liyinan926 @mrow4a

**Comment by liyinan926** [comment]
The last tagged version that works with Spark 2.3.x is https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/v1alpha1-0.4-2.3.x. Note that Spark 2.4.x is not compatible with 2.3.x when it comes to Spark on Kubernetes due to significant changes to the backend implementation and Docker image entrypoint.
